joint_pose:
  $(arg arm_id)_joint1: 0.01483612547710782
  $(arg arm_id)_joint2: 0.47600480179875204
  $(arg arm_id)_joint3: -0.9062344622985645
  $(arg arm_id)_joint4: -1.4831848455419392
  $(arg arm_id)_joint5: 0.38553734061479
  $(arg arm_id)_joint6: 1.8192255524857666
  $(arg arm_id)_joint7: -0.15823136083311534
  

