joint_pose:
  $(arg arm_id)_joint1: -0.0569540420312553
  $(arg arm_id)_joint2: 0.7262749495295654
  $(arg arm_id)_joint3:  -0.7409480239234257
  $(arg arm_id)_joint4:  -1.5678226040269923
  $(arg arm_id)_joint5: 0.46900809169373797
  $(arg arm_id)_joint6: 2.0716964525532853
  $(arg arm_id)_joint7: -0.154950302962876



