joint_pose:
  $(arg arm_id)_joint1: 0.0045555163605966505
  $(arg arm_id)_joint2: 0.5991078970966991
  $(arg arm_id)_joint3: -0.8830904549856379
  $(arg arm_id)_joint4: -1.6005111960278358
  $(arg arm_id)_joint5: 0.5212197775776001
  $(arg arm_id)_joint6: 1.9628001712533247
  $(arg arm_id)_joint7: -0.1888077745170502
  

