joint_pose:
  $(arg arm_id)_joint1: -0.06387546506342716
  $(arg arm_id)_joint2: 0.6983723381055752
  $(arg arm_id)_joint3: -0.751878364305483
  $(arg arm_id)_joint4:  -1.574633332781656
  $(arg arm_id)_joint5: 0.457437549030643
  $(arg arm_id)_joint6: 2.0619606516485853
  $(arg arm_id)_joint7: -0.16356829321637012



