joint_pose:
  $(arg arm_id)_joint1: -0.1518151175344546
  $(arg arm_id)_joint2: 0.7272022269191685
  $(arg arm_id)_joint3: -0.6298106996179716
  $(arg arm_id)_joint4: -1.5358921982450835
  $(arg arm_id)_joint5: 0.38414461930450944
  $(arg arm_id)_joint6: 2.0799141253708733
  $(arg arm_id)_joint7: -0.10627016204891697
