# main loop frequency [Hz] (should be as fast as F/T sensor publish frequency)
loop_rate: 1000.0

# waiting time after moving to each pose before taking F/T measurements
wait_time: 4.0

# Name of the moveit group
moveit_group_name: 'panda_arm'

# Name of the calib file
calib_file_name: 'franka_ft_calib_data.yaml'

# Name of the directory
calib_file_dir: '~/.ros/ft_calib'

# Name of file to store measurements
meas_file_name: 'franka_ft_calib_meas.txt'

# Name of the directory
meas_file_dir: '~/.ros/ft_calib'

# don't execute random poses
random_poses: false

# number of random poses
number_random_poses: 0

# the poses to which to move the arm in order to calibrate the F/T sensor
# format: [x y z r p y]  in meters, radians
# poses_frame_id sets the frame at which the poses are expressed
poses_frame_id: 'panda_link0'

pose0: [0.4, -0.4, 0.55, 0.0, 0.0, 0.0]
pose1: [0.4, -0.4, 0.55, 0.0, 0.0, -1.5707963267948966]
pose2: [0.4, -0.4, 0.55, 0.0, 0.5235987755982987, 0.0]
pose3: [0.4, -0.4, 0.55, -0.5235987755982987, 0.0, -1.5707963267948966]
pose4: [0.4, 0.4, 0.55, 6.409875621278547e-17, 0.5235987755982987, 1.0471975511965979]
pose5: [0.4, 0.4, 0.55, -0.5235987755982988, 0.0, -0.5235987755982989]
pose6: [0.4, 0.4, 0.55, -3.2049378106392724e-17, 0.5235987755982987, 2.0943951023931953]
pose7: [0.4, 0.4, 0.55, -0.5235987755982987, 0.0, 0.5235987755982987]
pose8: [0.4, 0.4, 0.55, 0.0, 0.5235987755982987, 3.141592653589793]
pose9: [0.4, 0.4, 0.55, -0.5235987755982988, 0.0, 1.5707963267948966]
pose10: [0.4, -0.4, 0.55, 3.204937810639273e-17, 0.5235987755982991, -2.0943951023931957]
pose11: [0.4, -0.4, 0.55, -0.5235987755982988, 0.0, 2.617993877991494]
pose12: [0.4, -0.4, 0.55, -6.409875621278547e-17, 0.5235987755982987, -1.0471975511965979]
pose13: [0.4, -0.4, 0.55, -0.5235987755982988, 0.0, -2.6179938779914944]
pose14: [0.4, -0.4, 0.55, 0.0, 1.0471975511965979, 0.0]
pose15: [0.4, -0.4, 0.55, -1.0471975511965979, 0.0, -1.5707963267948966]
pose16: [0.4, 0.4, 0.55, 1.1102230246251565e-16, 1.0471975511965979, 1.0471975511965979]
pose17: [0.4, 0.4, 0.55, -1.0471975511965976, 0.0, -0.523598775598299]
pose18: [0.4, 0.4, 0.55, 2.2204460492503126e-16, 1.0471975511965979, 2.0943951023931953]
pose19: [0.4, 0.4, 0.55, -1.0471975511965976, 0.0, 0.5235987755982987]
pose20: [0.4, 0.4, 0.55, -1.2325951644078307e-32, 1.0471975511965979, 3.141592653589793]
pose21: [0.4, 0.4, 0.55, -1.0471975511965976, 0.0, 1.5707963267948963]
pose22: [0.4, -0.4, 0.55, -1.110223024625156e-16, 1.0471975511965979, -2.094395102393196]
pose23: [0.4, -0.4, 0.55, -1.0471975511965976, 0.0, 2.617993877991494]
pose24: [0.4, -0.4, 0.55, -1.1102230246251565e-16, 1.0471975511965979, -1.0471975511965979]
pose25: [0.4, -0.4, 0.55, -1.0471975511965976, 0.0, -2.6179938779914944]
pose26: [0.4, -0.4, 0.55, -0.0, 1.5707963057214722, 0.0]
pose27: [0.4, -0.4, 0.55, -1.5707963267948966, 0.0, -1.5707963267948966]
pose28: [0.4, 0.4, 0.55, -1.0471975511965976, 1.5707963267948966, 0.0]
pose29: [0.4, 0.4, 0.55, -1.5707963267948966, 2.220446049250313e-16, -0.523598775598299]
pose30: [0.4, 0.4, 0.55, -2.0943951023931953, 1.5707963267948966, 0.0]
pose31: [0.4, 0.4, 0.55, -1.5707963267948966, 0.0, 0.5235987755982987]
pose32: [0.4, 0.4, 0.55, -3.141592653589793, 1.5707963057214722, 0.0]
pose33: [0.4, 0.4, 0.55, -1.5707963267948966, 0.0, 1.5707963267948963]
pose34: [0.4, -0.4, 0.55, 2.094395102393196, 1.5707963057214722, 0.0]
pose35: [0.4, -0.4, 0.55, -1.5707963267948966, 0.0, 2.617993877991494]
pose36: [0.4, -0.4, 0.55, 1.0471975511965976, 1.5707963267948966, 0.0]
pose37: [0.4, -0.4, 0.55, -1.5707963267948966, 0.0, -2.6179938779914944]
pose38: [0.4, -0.4, 0.55, 3.141592653589793, 1.0471975511965983, 3.141592653589793]
pose39: [0.4, -0.4, 0.55, -2.0943951023931953, 0.0, -1.5707963267948966]
pose40: [0.4, 0.4, 0.55, 3.141592653589793, 1.0471975511965983, -2.0943951023931957]
pose41: [0.4, 0.4, 0.55, -2.0943951023931953, 0.0, -0.5235987755982991]
pose42: [0.4, 0.4, 0.55, 3.141592653589793, 1.0471975511965983, -1.0471975511965979]
pose43: [0.4, 0.4, 0.55, -2.0943951023931953, 0.0, 0.5235987755982987]
pose44: [0.4, 0.4, 0.55, 3.141592653589793, 1.0471975511965983, -1.2246467991473535e-16]
pose45: [0.4, 0.4, 0.55, -2.0943951023931953, 0.0, 1.5707963267948966]
pose46: [0.4, -0.4, 0.55, -3.141592653589793, 1.0471975511965979, 1.0471975511965972]
pose47: [0.4, -0.4, 0.55, -2.0943951023931953, 0.0, 2.617993877991494]
pose48: [0.4, -0.4, 0.55, -3.141592653589793, 1.0471975511965983, 2.0943951023931957]
pose49: [0.4, -0.4, 0.55, -2.0943951023931953, 0.0, -2.617993877991494]
pose50: [0.4, -0.4, 0.55, 3.141592653589793, 0.5235987755982987, 3.141592653589793]
pose51: [0.4, -0.4, 0.55, -2.6179938779914944, 0.0, -1.5707963267948966]
pose52: [0.4, 0.4, 0.55, -3.141592653589793, 0.5235987755982987, -2.0943951023931953]
pose53: [0.4, 0.4, 0.55, -2.6179938779914944, 0.0, -0.5235987755982989]
pose54: [0.4, 0.4, 0.55, 3.141592653589793, 0.5235987755982987, -1.047197551196598]
pose55: [0.4, 0.4, 0.55, -2.6179938779914944, 0.0, 0.5235987755982986]
pose56: [0.4, 0.4, 0.55, 3.141592653589793, 0.5235987755982987, -1.224646799147353e-16]
pose57: [0.4, 0.4, 0.55, -2.6179938779914944, 0.0, 1.5707963267948966]
pose58: [0.4, -0.4, 0.55, -3.141592653589793, 0.5235987755982991, 1.0471975511965974]
pose59: [0.4, -0.4, 0.55, -2.6179938779914944, 2.220446049250313e-16, 2.617993877991494]
pose60: [0.4, -0.4, 0.55, 3.141592653589793, 0.5235987755982987, 2.0943951023931953]
pose61: [0.4, -0.4, 0.55, -2.6179938779914944, 0.0, -2.6179938779914944]
pose62: [0.4, -0.4, 0.55, 3.141592653589793, 0.0, 3.141592653589793]
pose63: [0.4, -0.4, 0.55, 3.141592653589793, 0.0, -1.5707963267948966]



# pose0: [0.4, 0.0, 0.40, 1.571, 1.571, 3.130]
# pose1: [0.4, 0.0, 0.40, 1.571, 0.8, 3.140]
# pose2: [0.4, 0.0, 0.40, 1.571, 0.4, 3.140]
# pose3: [0.4, 0.0, 0.40, 1.571, 0.0, 3.140]
# pose4: [0.4, 0.0, 0.40, 2.8, 0.0, 3.140]
# pose5: [0.4, 0.0, 0.40, 2.3, 0.0, 3.140]
# pose6: [0.4, 0.0, 0.40, 2.0, 0.0, 3.140]
# pose7: [0.4, 0.0, 0.40, 3.093, -0.012, -2.467]
# pose8: [0.4, 0.0, 0.40, 2.843, -0.012, -2.467]
# pose9: [0.4, 0.0, 0.40, 2.372, -0.012, -2.467]
# pose10: [0.4, 0.0, 0.40, 2.0, -0.012, -2.467]
# pose11: [0.4, 0.0, 0.40, 1.6, -0.012, -2.467]
# pose12: [0.4, 0.0, 0.40, 1.2, -0.012, -2.467]
# pose13: [0.4, 0.0, 0.40, 0.8, -0.012, -2.467]
# pose14: [0.4, 0.0, 0.40, 0.4, -0.012, -2.467]
# pose15: [0.4, 0.0, 0.40, 0.0, -0.012, -2.467]
# pose16: [0.4, 0.0, 0.40, 2.399, -0.568, 1.058]
# pose17: [0.4, 0.0, 0.40, 2.083, -0.858, 1.531]
# pose18: [0.4, 0.0, 0.40, 1.480, -0.962, 2.280]
# pose19: [0.4, 0.0, 0.40, 0.890, -0.748, 3.043]
# pose20: [0.4, 0.0, 0.40, 0.677, -0.409, -2.865]
# # pose21: [0.4, 0.0, 0.40, 0.607, -0.049, -2.576]
# pose21: [0.4, 0.0, 0.40, 0.621, 0.207, -2.396]
# pose22: [0.4, 0.0, 0.40, 2.252, 0.484, -2.121]
# pose23: [0.4, 0.0, 0.40, 2.258, -0.402, -2.726]
# # pose24: [0.4, 0.0, 0.40, 2.425, -0.685, -3.043]
# pose24: [0.4, 0.0, 0.40, 2.785, -0.898, 2.742]
# pose25: [0.4, 0.0, 0.40, -2.869, -0.919, 1.958]
# pose26: [0.4, 0.0, 0.40, 1.571, -0.4, 3.140]
# pose27: [0.4, 0.0, 0.40, 1.571, -0.8, 3.140]
# pose28: [0.4, 0.0, 0.40, 1.571, -1.571, 3.140]
# pose29: [0.4, 0.0, 0.30, 1.1, 0.0, 3.140]
# pose30: [0.4, 0.0, 0.30, 0.8, 0.0, 3.140]
# pose31: [0.4, 0.0, 0.30, 0.4, 0.0, 3.140]
# pose32: [0.4, 0.0, 0.30, 0.01, 0.0, 3.140]

# # pose10: [0.4, 0.0, 0.40, 2.0, -0.012, -2.467]
# # pose11: [0.4, 0.0, 0.40, 1.6, -0.012, -2.467]
# # pose12: [0.4, 0.0, 0.40, 1.2, -0.012, -2.467]
# # pose13: [0.4, 0.0, 0.40, 0.8, -0.012, -2.467]
# # pose14: [0.4, 0.0, 0.40, 0.4, -0.012, -2.467]
# # pose15: [0.4, 0.0, 0.40, 0.0, -0.012, -2.467]
# # pose16: [0.4, 0.0, 0.40, 2.399, -0.568, 1.058]
# # pose17: [0.4, 0.0, 0.40, 2.083, -0.858, 1.531]
# # pose18: [0.4, 0.0, 0.40, 1.480, -0.962, 2.280]
# # pose19: [0.4, 0.0, 0.40, 0.890, -0.748, 3.043]
# # pose20: [0.4, 0.0, 0.40, 0.677, -0.409, -2.865]
# # pose21: [0.4, 0.0, 0.40, 0.607, -0.049, -2.576]
# # pose22: [0.4, 0.0, 0.40, 0.621, 0.207, -2.396]
# # pose23: [0.4, 0.0, 0.40, 2.252, 0.484, -2.121]
# # pose24: [0.4, 0.0, 0.40, 2.258, -0.402, -2.726]
# # pose25: [0.4, 0.0, 0.40, 2.425, -0.685, -3.043]
# # pose26: [0.4, 0.0, 0.40, 2.785, -0.898, 2.742]
# # pose27: [0.4, 0.0, 0.40, -2.869, -0.919, 1.958]

# # pose4: [0.4, 0.0, 0.40, 1.571, -0.4, 3.140]
# # pose5: [0.4, 0.0, 0.40, 1.571, -0.8, 3.140]
# # pose6: [0.4, 0.0, 0.40, 1.571, -1.571, 3.140]
# # pose10: [0.4, 0.0, 0.30, 1.1, 0.0, 3.140]
# # pose11: [0.4, 0.0, 0.30, 0.8, 0.0, 3.140]
# # pose12: [0.4, 0.0, 0.30, 0.4, 0.0, 3.140]
# # pose13: [0.4, 0.0, 0.30, 0.01, 0.0, 3.140]